save:
  basedir: 'experiments/profile/log_gvrh'
  outdir: 'smooth_dila'
  
data:
  data_loc: 'matbench_data/matbench_log_gvrh'
  folds: [0]
  target_name: 'log10(G_VRH)'
  test_size: 0.1
  batch_size: 64
  reweight: 'sqrt_inv'
  shuffle: true
  seed: 39
  cutoff: 5
  add_z_bond_coord: false
  atom_features: 'embed'
  edge_embed_size: 10

model:
  state_input_shape: 2

train:
  epoch_range: 500
  weighted_loss: false
  alpha_metric: 'dcor'
  dil_inform: true
  profile_runtime: true
  dil_config:
    method: 'smooth'
    base_metric: 'huber'
    lambda: 0.5
    momentum: 0.1
    warmup_epochs: 10
    aware_threshold: 0.86
  
hpo:
  trials: 30
  tune_dila: true

multi_runs: 3  # Number of multi-seed runs after HPO

optimiser:
  name: 'AdamW'

scheduler:
  name: 'CosineAnnealingLR'
  
loss:
  loss: 'WeightedHuberLoss'
